Drop TABLE AUTOT

CREATE TABLE AUTOT(ID INTEGER IDENTITY (1,1) PRIMARY KEY, merkki VARCHAR(50), malli Varchar(50), vuosimalli INTEGER);

CREATE TABLE HUOLTOTILAUS(id INTEGER IDENTITY (1,1) PRIMARY KEY, asiakas_id INTEGER REFERENCES ASIAKKAAT ON DELETE CASCADE, varosa_id INTEGER REFERENCES VARAOSAT ON DELETE CASCADE,auto_id INTEGER REFERENCES AUTOT ON DELETE CASCADE, toimitettu BIT DEFAULT 0);
